---
require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - _snippets/*
  
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - Rakefile
    - app/controllers/**/*

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - app/controllers/auth.rb

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

# Style/HashSyntax:
#   Enabled: true
#   Exclude:
#     - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrations/**/*
    - Rakefile

Style/RedundantRegexpEscape:
  Enabled: true
  Exclude:
    - app/forms/form_base.rb
